# Generated by Django 6.1 on 2026-08-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_photos/')),
                ('steps', models.TextField(help_text='Numbered steps')),
                ('recipe_type', models.CharField(choices=[('dinner', 'Dinner'), ('lunch', 'Lunch'), ('breakfast', 'Breakfast'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('side', 'Side Dish'), ('other', 'Other')], default='dinner', max_length=20)),
                ('is_meal_preppable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit', models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('fl_oz', 'Fluid Ounce'), ('g', 'Gram'), ('oz', 'Ounce'), ('pinch', 'Pinch'), ('piece', 'Piece'), ('can', 'Can'), ('package', 'Package'), ('whole', 'Whole'), ('', 'N/A')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag'),
        ),
    ]
