# Generated by Django 6.1 on 2026-09-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('frozen', 'Frozen'), ('produce', 'Produce'), ('dairy', 'Dairy'), ('meat_seafood', 'Meat/Seafood'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('beverages', 'Beverages'), ('cleaning', 'Cleaning'), ('housewares', 'Housewares'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
