# Generated by Django 6.1 on 2026-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('fl_oz', 'Fluid Ounce'), ('g', 'Gram'), ('oz', 'Ounce'), ('pinch', 'Pinch'), ('piece', 'Piece'), ('can', 'Can'), ('package', 'Package'), ('whole', 'Whole'), ('', 'N/A')], max_length=20),
        ),
    ]
