# Generated by Django 6.1.1 on 2026-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shoppinglistitem_amount_shoppinglistitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipe_videos/'),
        ),
    ]
