# Generated by Django 6.1.1 on 2026-09-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_source_url_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='category',
            field=models.CharField(choices=[('frozen', 'Frozen'), ('produce', 'Produce'), ('dairy', 'Dairy'), ('meat_seafood', 'Meat/Seafood'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('beverages', 'Beverages'), ('cleaning', 'Cleaning'), ('housewares', 'Housewares'), ('health_personal', 'Health & Personal Care'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='category',
            field=models.CharField(choices=[('frozen', 'Frozen'), ('produce', 'Produce'), ('dairy', 'Dairy'), ('meat_seafood', 'Meat/Seafood'), ('bakery', 'Bakery'), ('pantry', 'Pantry'), ('beverages', 'Beverages'), ('cleaning', 'Cleaning'), ('housewares', 'Housewares'), ('health_personal', 'Health & Personal Care'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
